# ===================================================================
# DATABASE
# ===================================================================

spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:31274/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

spring.datasource.username=root

spring.datasource.password=QZnVFIJPZaVrrDTSRECFlMdyqGrgBtEr

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# JPA / HIBERNATE
# ===================================================================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# SERVER
# ===================================================================

server.port=${PORT:8080}

# ===================================================================
# UTF-8
# ===================================================================

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true